### ISSUE TITLE
Hologram not compiling docs

### ISSUE THREAD

**Issue by gilesbutler** [trulia/hologram#158]
I get this error when i run hologram, any ideas?

```
C:/Ruby21/lib/ruby/gems/2.1.0/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:191:in `ensure in write_page': undefined method `close' for nil:NilClass (NoMethodError)
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:191:in `write_page'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:171:in `block in write_docs'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:157:in `each'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:157:in `write_docs'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:123:in `build_docs'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hologram-1.2.0/lib/hologram/doc_builder.rb:65:in `build'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hologram-1.2.0/lib/hologram/cli.rb:38:in `build'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hologram-1.2.0/lib/hologram/cli.rb:30:in `run'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/hologram-1.2.0/bin/hologram:6:in `<top (required)>'
        from C:/Ruby21/bin/hologram:23:in `load'
        from C:/Ruby21/bin/hologram:23:in `<main>'
```

**Comment by Silom** [comment]
Good for you I have the informations now. Its a year ago but I got the same problem. I deleted one of my doc folders and now I get the same error. Is there some kind of cache you use? That would be the only problem I can think of..

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error in plugin 'gulp-hologram'
/Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:247:in `ensure in write_page': undefined method `close' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:247:in `write_page'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:199:in `block in write_docs'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:185:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:185:in `write_docs'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:147:in `build_docs'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/doc_builder.rb:87:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/cli.rb:38:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/lib/hologram/cli.rb:30:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-1.4.0/bin/hologram:6:in `<top (required)>'
	from /usr/local/bin/hologram:23:in `load'
	from /usr/local/bin/hologram:23:in `<main>'

    at Socket.<anonymous> (/Users/xxx/node_modules/gulp-hologram/index.js:96:30)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
```

As you can see I have the gulp task running, but its not crashing the Ruby app.

**Comment by jdcantrell** [comment]
No we don't use caching, is there any chance you can share the code base you run hologram on?
