### ISSUE TITLE
invalid byte sequence in UTF-8 (ArgumentError) 

### ISSUE THREAD

**Issue by MP3en** [trulia/hologram#56]
Hallo,
since i installed osx mavericks i get the following error message: Maybe sombody know what to do.

```
/Library/Ruby/Gems/2.0.0/gems/hologram-0.6.0/lib/hologram.rb:216:in `scan': invalid byte sequence in UTF-8 (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/hologram-0.6.0/lib/hologram.rb:216:in `process_file'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-0.6.0/lib/hologram.rb:202:in `block in process_files'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-0.6.0/lib/hologram.rb:198:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-0.6.0/lib/hologram.rb:198:in `process_files'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-0.6.0/lib/hologram.rb:191:in `block in process_dir'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-0.6.0/lib/hologram.rb:184:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-0.6.0/lib/hologram.rb:184:in `process_dir'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-0.6.0/lib/hologram.rb:127:in `build_docs'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-0.6.0/lib/hologram.rb:92:in `init'
	from /Library/Ruby/Gems/2.0.0/gems/hologram-0.6.0/bin/hologram:5:in `<top (required)>'
	from /usr/bin/hologram:23:in `load'
	from /usr/bin/hologram:23:in `<main>'
```

**Comment by breams** [comment]
Just came across this problem and our issue was with empty files in the source path.

**Comment by jdcantrell** [comment]
Thanks for adding more details, we'll look into this.

**Comment by soulpimp** [comment]
Is there any word on if this has been fixed or if there is a workaround for this issue?
running: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]

**Comment by jdcantrell** [comment]
Can you share a source file that causes this?

**Comment by pflannery** [comment]
I had the same issue and found that comments with text like Léonie seem to cause this issue

The below example was causing the error but without Léonie it worked.
```js
/* Replace the div at the head with a button element. This is based on feedback from Léonie Watson.
 * The button has all of the accessibility hooks that are used by screen readers and etc.
 * We do this in the JavaScript because if the JavaScript is not active then the button shouldn't
 * be there as there is no JS to handle the click event.
 */
```

Hope that helps

**Comment by ajaykarwal** [comment]
I had the same issue today and found it was related to Unicode characters.

I used this regex pattern `[^\x00-\x7f]` to find all Unicode characters in my `.scss` files and either changed or deleted them

Source: http://devblog.appriver.com/removing-hidden-unicode-characters-from-visual-studio/
